version: '3.8'

services:
  php:
    container_name: '${CONTAINER_NAME}_php'
    build:
      context: ./
    volumes:
      - ./:/var/www/html
    networks:
      - backend-network
    depends_on:
      - mongodb

  mongodb:
    container_name: '${CONTAINER_NAME}_mongodb'
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend-network

  nginx:
    container_name: '${CONTAINER_NAME}_nginx'
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    ports:
      - "${REMOTE_SERVER_PORT}:8000"
    depends_on:
      - php
      - mongodb
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge